config/routes.rb
Rails.application.routes.draw do
  
  resources :user_contents do
    collection do
      get "user_contents_count" 
    end
  end

  resources :user_artists do
     collection do
      get "user_artists_count" 
      get "artist_index"
    end
  end
    
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  namespace :admin do 
    resources :instagramposters, :twitterposters, :artists
  end

  get 'home/index'

  root 'home#index'

end

app/models/user_artist.rb
class UserArtist < ActiveRecord::Base
  belongs_to :user
  belongs_to :artist

  def self.get_id_from_content(user, artist)
	where(user_id: user).where(artist_id: artist).first.id
  end

  def self.find_by_user_artist(user, artist)
	where(user_id: user).where(artist_id: artist).first
  end


  
end

app/controllers/user_artists_controller.rb
class UserArtistsController < ApplicationController
  before_action :set_user_artist, only: [:show, :edit, :update, :destroy]
  before_filter :set_counts
  # after_filter :set_content, only: [:create, :destroy]

  # GET /user_artists
  # GET /user_artists.json
  def index
    # @user_artists = current_user.user_artists.page(params[:page]).per(10)
    if params[:artist_id]
      @contents = Content.artists(current_user).where(artist_id: params[:artist_id]).page(params[:page]).per(10)
    else
      @contents = Content.artists(current_user).all.page(params[:page]).per(10)
    end
       
  end

  def artist_index
    @user_artists = current_user.artists.all.page(params[:page]).per(10)
    if params[:scoped]
      @contents = Content.by_artist_for_user_collection(current_user).all.page(params[:page]).per(21)
    end
  end  
  

  def user_artists_count
    @count = current_user.artists.count    
    render json: @count
  end

  # GET /user_artists/1
  # GET /user_artists/1.json
  def show
  end

  # GET /user_artists/new
  def new
    @user_artist = UserArtist.new
  end

  # GET /user_artists/1/edit
  def edit
  end

  # POST /user_artists
  # POST /user_artists.json
  def create
    @user_artist = UserArtist.new(user_artist_params)
    @contents = Content.all.page(params[:page]).per(10)
     # @count_artists = current_user.artists.count 
    
    if @user_artist.save
      respond_to do |format|
        set_counts
        @content = Content.where(id: params[:content_id]).first
        format.html { redirect_to root_url, notice: 'Artist was successfully created.' }
        format.json { render json: @user_artist }
        format.js
      end
       
       # render json: @user_artist
      else
        # format.html { render :new }
        # format.json { render json: @user_artists.errors, status: :unprocessable_entity }
        render json: @user_artist.errors
      end
  end

  # PATCH/PUT /user_artists/1
  # PATCH/PUT /user_artists/1.json
  def update
    respond_to do |format|
      if @user_artist.update(user_artist_params)
        format.html { redirect_to @user_artist, notice: 'User artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_artist }
      else
        format.html { render :edit }
        format.json { render json: @user_artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_artists/1
  # DELETE /user_artists/1.json
  def destroy
     @user_artists = current_user.artists.all.page(params[:page]).per(10)
     # @contents = Content.all.page(params[:page]).per(10)
    
     # if params[:scoped]
      # @contents = Content.by_artist_for_user_collection(current_user).all.page(params[:page]).per(21)
     # else
      @contents = Content.all.page(params[:page]).per(10)
     # end

    if @user_artist.destroy
        respond_to do |format|
          if params[:scoped]
            @contents = Content.by_artist_for_user_collection(current_user).all.page(params[:page]).per(21)
          else
            @content = Content.where(id: params[:content_id]).first
          end
          set_counts          
          format.html { redirect_to home_index_path, notice: 'Artist was successfully destroyed.' }
          format.json { render json: @user_artist }      
          format.js
        end
      
      # render json: @user_artist
    else
      render json: @user_artist.errors
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_artist
      if params[:user_id] && params[:artist_id]
        @user_artist = UserArtist.find_by_user_artist(user_id: params[:user], artist_id: params[:artist_id])
      else
        @user_artist = UserArtist.find(params[:id])
      end

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_artist_params
      params.require(:user_artist).permit(:user_id, :artist_id, :scoped, :user_artists_attributes, :artists_attributes)
    end

    def set_content
      @content = Content.where(id: params[:content_id]).first
    end

    def set_counts
      if user_signed_in?
        @count_artists = current_user.artists.count
        @count_favorites = Content.favorites(current_user).count
      else
        @count_artists = ""
        @count_favorites = ""
      end 
    end
end

app/helpers/user_artists_helper.rb
module UserArtistsHelper
end

app/views/user_artists/_form.html.erb
<%= form_for(@user_artist) do |f| %>
  <% if @user_artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_artist.errors.count, "error") %> prohibited this user_artist from being saved:</h2>

      <ul>
      <% @user_artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :artist_id %><br>
    <%= f.text_field :artist_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_artists/_pagination.html.erb
<%= paginate @user_artists %>

app/views/user_artists/_user_artist.html.erb
<div id='<%= a.id %>' class='artist'>
     <div class="large-12 columns">

                <div class='panel large-6 columns' style='height:350px'>

                     <h4><%= a.artist_name %></h4> 
                     <h5><%= "Full Name:" + a.first_name + " " + a.last_name %></h5>                    
                     <strong>Artist Bio: </strong><blockquote  style='text-overflow: ellipsis;'>
                     Lorem ipsum dolor sit amet, consecsadfasfsadfsadfsfdtetur adipisicing elit, sed do eiusmod
                     tempor incididunt ut labor sint occaecat cupidatat non
                     proident, sunt in culpa qui officia deserunt mollit anim id est laborum.t occaecat cupidatat non
                     proident, sunt in culpa qui officia deset occaecat cupidatat non
                     proident, sunt in culpa qui officia deset</blockquote>                     

                 <p>
                    <%= link_to "View All Content", user_artists_path(artist_id: a.id), class: "button radius round success tiny btnViewArtistContent"  %>
                    <%= link_to "Unfollow", user_artist_path(a.user_artists.first.id), method: :delete, class: "button radius round alert tiny btnUnfollow",
                    remote: true, id: 'btnUnfollow'  %>

                    <% unless Content.favorites(current_user).where(artist_id: a.id).blank? %>
                    <%= link_to "View Saved Content", user_contents_path(artist_id: a.id), class: "button radius round info tiny btnViewSavedContent", style: 'color:white;'  %>
                    <% end %>
                  <%#need to get this from twiter= image_tag a.first.profil_image_url.to_s %>

                 </p>                  

               </div>

           <!-- <fieldset><legend>Most Recent Post Pic</legend> -->
           <div class='large-6 columns'><%= image_tag a.contents.first.image_url(:main).to_s, style: 'height:350px' %></div>
           <!-- </fieldset> -->



     </div>
    </div>

app/views/user_artists/_user_artists.html.erb
<% if params[:scoped] %>

      <% @contents.each do |c| %>
       <div id='timeline' class='post large-4 columns'>

         <div class="panel contents">      
      
          <div class='action_buttons <%= c.id %> text-center'>
             <%= render partial: "home/action_buttons", locals: { :c => c }  %>         
          </div>

              <div class='post_image text-center'>
                <%#= link_to "#", 'data-reveal-id' => 'modal', remote: true do %>
                  <%= image_tag c.image_url(:main).to_s, class: '.test' %>
                <%# end %>              
              </div>
              

                <div class='row'>  
                  <div class='bottom-info' style='float:left; margin: 10px'>
                   <%= link_to user_artists_path(artist_id: c.artist.id) do %>
                     <h4><%= c.artist.artist_name %></h4>
                     <h5 style='word-wrap:break-word;'><%= c.user_name.to_s + " via " + c.social_media_site.to_s %></h5>
                     <h6><%= c.created_at.to_date %></h6>                
                   <% end %> 
                   </div>
                 
                   <div class='profile_image' style='float:right'>
                     <% if c.twitterposter %>
                     <%= image_tag c.twitterposter.profile_image_url(:thumb).to_s, size: '100x100', style: 'margin:10px 16px 0 0' %>
                     <% else %>
                     <%= image_tag c.instagramposter.profile_image_url(:thumb).to_s, size: '100x100', style: 'margin:10px 16px 0 0'  %>
                     <% end %>
                   </div>
               </div>
      </div>
    </div>
      <% end %>

<% else %>

<% @user_artists.each do |a| %>

   <%= render 'user_artist', a: a %>

     <% end %>

<% end %>

app/views/user_artists/_user_artists_content.html.erb
<% @user_artists.each do |c| %>
  
<div id='timeline1' class='artist_post large-4 columns'>
  <div class="panel">                                 
      <%= link_to "#", 'data-reveal-id' => 'modal', remote: true do %>
        <h5><%= c.user_name.to_s + " via " + c.social_media_site.to_s %></h5>
        <h6><%= c.created_at.to_date %></h6>        
        <blockquote  style='text-overflow: ellipsis;'><%= c.text %></blockquote>            
      <% end %>
        <% if user_signed_in? %>
           <% if c.following(current_user) == true %>
             <%= button_tag :following, class: "button radius round tiny disabled btnFollow #{c.artist_id}", 
             'data-user' => current_user.id,'data-artist' => c.artist.id %>
           <% else %>
             <%= button_tag :follow, class: "button radius round tiny btnFollow #{c.artist_id}", 'data-user' => current_user.id, 
             'data-artist' => c.artist.id %>
           <% end %>

           <% if c.favorite(current_user) == true %>

           <%= button_tag "saved to favorites", class: "button radius round tiny info disabled btnFavorite",id: "#{c.id}fav", 'data-user' => current_user.id, 
             'data-content' => c.id %>            
           <% else %>
           <%= button_tag "Add to favorites", class: "button radius round tiny success btnFavorite", id: "#{c.id}fav",'data-user' => current_user.id, 'data-content' => c.id %>
           <% end %>
         <% end %>

        <p>

    <%= link_to "#", 'data-reveal-id' => 'modal', remote: true do %>
      <%= image_tag c.image_url(:main).to_s %>
    <% end %>
    </p>
  </div>
 </div>


 <% end %>

 <%= render 'layouts/modal' %>

app/views/user_artists/artist_index.html.erb
<h1>My Artists</h1>

<div class='row'>
  <div id='user_artists_container' class="user_artists active" id="panel2-1">      
    
    <%= render 'user_artists', locals: {:contents => @contents} %>

  </div>
 </div>

<p>
  <div class='pagination_scroll row large-12 columns' style='margin-top:30px;'>
    <%= paginate @user_artists %>
  </div>
</p>

<script type="text/javascript">


// toggleScroll("user_artists", "artist");







</script>

app/views/user_artists/create.js.erb
$("."+"<%= @user_artist.artist_id %>").html("<%= escape_javascript(link_to 'following', user_artist_path(UserArtist.where(user_id: current_user.id).where(artist_id: @user_artist.artist_id).first.id), method: 'delete', class: 'button radius round tiny following_state info', 
           remote: true) %>")
$(".count").html("<%= escape_javascript(render('layouts/counts')) %>");
$("#flash_messages").html("<%= escape_javascript(render('layouts/messages')) %>");

app/views/user_artists/destroy.js.erb
$("."+"<%= @user_artist.artist_id %>").html("<%= escape_javascript(link_to 'follow', user_artists_path(user_artist: {user_id: current_user.id, artist_id: @user_artist.artist_id}),  method: 'post', action: :create, class: 'button radius round tiny alert', remote: true) %>")

$(".count").html("<%= escape_javascript(render('layouts/counts')) %>");
$("#flash_messages").html("<%= escape_javascript(render('layouts/messages')) %>");

// $("#user_artists_container").html("<%= escape_javascript(render('user_artists/user_artists')) %>");
$("#user_artists_container").html("")
$("#user_artists_container").html("<%= j render('user_artists') %>");


$("#"+"<%= @user_artist.artist_id %>").html("")



<% if params[:show] %>
$(window.location.replace("/user_artists/artist_index"))
<% end %>

<% unless @contents.count > 0 %>
$(window.location.replace("/"))
<% end %>

app/views/user_artists/edit.html.erb
<h1>Editing user_artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_artist %> |
<%= link_to 'Back', user_artists_path %>

app/views/user_artists/index.html.erb
<h1><%= @contents.first.artist.artist_name + " - " + "All content" %></h1>
<%= link_to "Unfollow", user_artist_path(UserArtist.where(user_id: current_user.id).where(artist_id: @contents.first.artist_id).first.id, show: true), method: 'delete', class: "button radius round tiny following_state btnFollow info", remote: true %>


<div class='row'>
  <div id='user_artists_posts' class="user_artists_posts active" id="panel2-1">      
      <%#= render 'user_artists_content' %>
      <%= render 'home/scoped_contents_artist' %>
  </div>
 </div>




<p>
  <div class='pagination_scroll row large-12 columns' style='margin-top:30px;'>
    <%= render 'home/pagination' %>
  </div>
</p>

<script type="text/javascript">


// toggleScroll("user_artists_posts", "artist_post");

  // $element_artist = $('#user_artists_posts')

  //   $element_artist.infinitescroll({
   
  //     navSelector  : "nav.pagination",            
  //                    // selector for the paged navigation (it will be hidden)
  //     nextSelector : "nav.pagination a[rel=next]",    
  //                    // selector for the NEXT link (to page 2)
  //     itemSelector : "#user_artists_posts div.artist_post",

  //     loading: {          
  //           img: '../assets/loading.gif',                              
  //           finished: undefined,
  //           msgText: "",
  //           finishedMsg: "",
  //           selector: '#loader',
  //           speed: 'fast'
  //     }

     
  //  });





</script>

app/views/user_artists/index.js.erb
$("#flash_messages").html("<%= escape_javascript(render('layouts/messages')) %>");

$("#user_artists_posts").html("<%= escape_javascript(render('user_artists_content')) %>");

$(".pagination_scroll").html("<%= escape_javascript(render('pagination')) %>");

app/views/user_artists/new.html.erb
<h1>New user_artist</h1>

<%= render 'form' %>

<%= link_to 'Back', user_artists_path %>

app/views/user_artists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_artist.user %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @user_artist.artist %>
</p>

<%= link_to 'Edit', edit_user_artist_path(@user_artist) %> |
<%= link_to 'Back', user_artists_path %>