config/routes.rb
Rails.application.routes.draw do
  
  resources :user_contents do
    collection do
      get "user_contents_count" 
    end
  end

  resources :user_artists do
     collection do
      get "user_artists_count" 
      get "artist_index"
    end
  end
    
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  namespace :admin do 
    resources :instagramposters, :twitterposters, :artists
  end

  get 'home/index'

  root 'home#index'

end

app/models/artist.rb
class Artist < ActiveRecord::Base
	has_many :twitterposters
	has_many :instagramposters	
	has_many :contents
	has_many :user_artists

	accepts_nested_attributes_for :twitterposters
	accepts_nested_attributes_for :instagramposters
	
end

app/controllers/admin/artists_controller.rb
module Admin
  class ArtistsController < ApplicationController
    

    # http_basic_authenticate_with name: Rails.application.secrets.admin_name, password: Rails.application.secrets.admin_password
    before_filter :admin_authentication

    before_action :set_artist, only: [:show, :edit, :update, :destroy]

    # GET /artists
    # GET /artists.json
    def index
      @artists = Artist.all
    end

    # GET /artists/1
    # GET /artists/1.json
    def show

      respond_to do |format|
        format.html
        format.json { render json: @artist.id }      
      end
    end

    # GET /artists/new
    def new
      @artist = Artist.new
      @artist.twitterposters.build
      @artist.instagramposters.build
    end

    # GET /artists/1/edit
    def edit
      
    end

    # POST /artists
    # POST /artists.json
    def create
      @artist = Artist.new(artist_params)

      respond_to do |format|
        if @artist.save
          format.html { redirect_to [:admin, @artist], notice: 'Artist was successfully created.' }
          format.json { render :show, status: :created, location: @artist }
        else
          format.html { render :new }
          format.json { render json: @artist.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /artists/1
    # PATCH/PUT /artists/1.json
    def update
      respond_to do |format|
        if @artist.update(artist_params)
          format.html { redirect_to [:admin, @artist], notice: 'Artist was successfully updated.' }
          format.json { render :show, status: :ok, location: @artist }
        else
          format.html { render :edit }
          format.json { render json: @artist.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /artists/1
    # DELETE /artists/1.json
    def destroy
      @artist.destroy
      respond_to do |format|
        format.html { redirect_to admin_artists_url, notice: 'Artist was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_artist
        @artist = Artist.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def artist_params
        params.require(:artist).permit(:artist_name, :first_name, :last_name, 
          :twitterposters_attributes => [:id, :user_id, :screen_name, :artist_id, :profile_image, :remote_profile_image_url], 
          :instagramposters_attributes => [:id, :ig_id, :screen_name, :artist_id, :profile_image,:remote_profile_image_url])
      end
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/admin/artists/_form.html.erb
<%= form_for [:admin, @artist] do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <legend>Artist Info</legend>
    <div class="field">

      <%= f.label :artist_name %><br>
      <%= f.text_field :artist_name %>
    </div>
    <div class="field">
      <%= f.label :first_name %><br>
      <%= f.text_field :first_name %>
    </div>
    <div class="field">
      <%= f.label :last_name %><br>
      <%= f.text_field :last_name %>
    </div>

  </fieldset>

 <fieldset> <legend>Twitter</legend>
  <%= f.fields_for :twitterposters do |t| %>

    <%= t.hidden_field :id %>
      <div class="field">
      <%= t.label "twitter id" %><br>
      <%= t.number_field :user_id %>
    </div>
    <div class="field">
      <%= t.label :screen_name %><br>
      <%= t.text_field :screen_name %>
    </div>
    <%= t.hidden_field :artist_id %>
  
    <div class="field">
      <%= t.label :remote_profile_image_url %><br>
      <%= t.text_field :remote_profile_image_url %>    
    </div>
  <% end %>
</fieldset>

<fieldset>
  <legend>Instagram</legend>
  <%= f.fields_for :instagramposters do |ig| %>
  <div class="field">
    <%= ig.hidden_field :id %>


    <%= ig.label "instagram id" %><br>
    <%= ig.number_field :ig_id %>
  </div>
  <div class="field">
    <%= ig.label :screen_name %><br>
    <%= ig.text_field :screen_name %>
  </div>
 
    <%= ig.hidden_field :artist_id %>
 
  
  <div class="field">
    <%= ig.label :remote_profile_image_url %><br>
    <%= ig.text_field :remote_profile_image_url %>   
  </div>

  <% end %>

</fieldset>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/artists/edit.html.erb
<h1>Editing artist</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_artist_path(@artist) %> |
<%= link_to 'Back', admin_artists_path %>

app/views/admin/artists/index.html.erb
<h1>Listing artists</h1>

<table>
  <thead>
    <tr>
      <th>Artist name</th>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= artist.artist_name %></td>
        <td><%= artist.first_name %></td>
        <td><%= artist.last_name %></td>
        <td><%= link_to 'Show', admin_artist_path(artist) %></td>
        <td><%= link_to 'Edit', edit_admin_artist_path(artist) %></td>
        <td><%= link_to 'Destroy', admin_artist_path(artist), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artist', new_admin_artist_path %>

app/views/admin/artists/new.html.erb
<h1>New artist</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_artists_path %>

app/views/admin/artists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Artist name:</strong>
  <%= @artist.artist_name %>
</p>

<p>
  <strong>First name:</strong>
  <%= @artist.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @artist.last_name %>
</p>

<%= link_to 'Edit', edit_admin_artist_path(@artist) %> |
<%= link_to 'Back', admin_artists_path %>