config/routes.rb
Rails.application.routes.draw do
  
  resources :user_contents do
    collection do
      get "user_contents_count" 
    end
  end

  resources :user_artists do
     collection do
      get "user_artists_count" 
      get "artist_index"
    end
  end
    
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  namespace :admin do 
    resources :instagramposters, :twitterposters, :artists
  end

  get 'home/index'

  root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 
  def index
     			 
	if !params[:search_field].blank? || !params[:search_field].nil? || !params[:search_field] == ""
	
				
		query = Content.search(params[:search_field])
		@contents = Kaminari.paginate_array(query).page(params[:page]).per(21)
		
		if @contents.length == 0
			flash.now[:alert] = "Sorry, no results found"			
		else
			unless params[:page]
				flash.now[:notice] = "Your search yieled #{query.count} results!"
			end
		end		
	else
		@contents = Content.all.page(params[:page]).per(21)
	end

	if params[:clear] 
		flash.now[:notice] = "Cleared"
		
		@contents = Content.all.page(params[:page]).per(21)	
		redirect_to "/"

		
	end
	 
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_action_buttons.html.erb
<!-- <div style='clear:both'></div> -->
 <div class='large-12 columns'>
   



<%= markdown(c.text) %>

<%#= markdown(@project.projectdesc) %>


    <div class='large-4 columns <%= c.artist_id %>'>
    <% if user_signed_in? %>

      <% if c.following(current_user) == true %>

      <% if params[:scoped] %>
       <%= link_to "unfollow", user_artist_path(id: UserArtist.where(user_id: current_user.id).where(artist_id: c.artist_id).first.id, scoped: true), method: 'delete', class: "button radius round tiny following_state info", 
           remote: true %>      
      
      <% else %>

        <%= link_to "unfollow", user_artist_path(UserArtist.where(user_id: current_user.id).where(artist_id: c.artist_id).first.id), method: 'delete', class: "button radius round tiny following_state info", 
           remote: true %>      

      <% end %>
      


       <% else %>
          <%= link_to "follow", user_artists_path(user_artist: {user_id: current_user.id, artist_id: c.artist_id}),  method: 'post', action: :create, class: "button radius round tiny alert ", remote: true %>
       <% end %>

    <% else %>
         <%= link_to "follow", nil, 'data-reveal-id' => 'modal', id: 'btnAddArtist_login', class: "button radius round tiny alert", remote: true %> 
         
    <% end %>

     </div>
  

     <div class='large-8 columns content_btns'>
    
    <% if user_signed_in? %>
       
       <% if c.favorite(current_user.id) == true %>
        <%= link_to "Saved to favorites", user_content_path(UserContent.where(:user_id=>current_user.id).where(:content_id=>c.id).first.id), 
        method: 'delete', class: 'button radius round tiny info', remote: true %> 
         <% else %>
         <%= link_to "Add to favorites", user_contents_path(user_content: {user_id: current_user.id, content_id: c.id }), method: 'post', action: :create, class: 'button radius round tiny success', remote: true %>
       <% end %>

    <% else %>
       <%= link_to "Add to favorites",nil, 'data-reveal-id' => 'modal', id: 'btnAddFavorite_login', class: 'button radius round tiny success', remote: true %> 
    <% end %>
     </div>



</div>
 <!-- <div style='clear:both'></div> -->

app/views/home/_action_buttons_scoped.html.erb
<% if c.favorite(current_user.id) == true %>

  <%= link_to "Remove from favorites", user_content_path(UserContent.where(:user_id=>current_user.id).where(:content_id=>c.id).first.id, :scoped=>true, artist_id: c.artist_id), 
  method: 'delete', class: 'button radius round tiny info', remote: true %> 

   <% else %>


   <%= link_to "Add to favorites", user_contents_path(user_content: 
   {user_id: current_user.id, content_id: c.id, artist_id: c.artist_id},:scoped=>true), 
   method: 'post', action: :create, class: 'button radius round tiny success', remote: true %>

 <% end %>

app/views/home/_authentication.html.erb
<% if user_signed_in? %>
	 
	     <li class="has-dropdown">
	      <a class="active" href="#"><%= current_user.username %></a>
	        <ul class="dropdown">	          
	          <li><%= link_to 'Edit profile', edit_user_registration_path,style: 'color:white;' %></li>
	          <li><%= link_to "Logout", destroy_user_session_path, method: :delete,style: 'color:white;' %></li>	          
	        </ul>
	    </li>

	 
<% else %>
 <%#= link_to "Sign up", new_user_registration_path %> |
 <%#= link_to "Login", new_user_session_path %>

  <li style='color:white;margin-top:10px'><span>Sign in through</span></li> 
 	<li><%= link_to image_tag("twitter-icon.png", :border => 0, :size=>'35x35'), user_omniauth_authorize_path(:twitter), style: 'color:white;' %></li>
    <!-- <li class='divider'></li> -->
    <li><%= link_to image_tag("instagram_icon.png", :border => 0, :size=>'35x35'), user_omniauth_authorize_path(:twitter), style: 'color:white;' %></li>
    <!-- <li class='divider'></li> -->
    <li><%= link_to image_tag("google-icon.ico", :border => 0, :size=>'35x35'), user_omniauth_authorize_path(:twitter), style: 'color:white;' %></li>
 

<% end %>

app/views/home/_content_old.html.erb
<% @contents.each do |c| %>
	
<div id='timeline' class='post large-4 columns'>

 	<div class="panel">			 							              
 	<!-- link to below is to activate modal -->
 	<%#= link_to "#", 'data-reveal-id' => 'modal', remote: true do %>
 	<%= link_to "#",  remote: true do %>
       	<h4><%= c.artist.artist_name %></h4>
        <h5><%= c.user_name.to_s + " via " + c.social_media_site.to_s %></h5>
        <h6><%= c.created_at.to_date %></h6>        
        <blockquote  style='text-overflow: ellipsis;'><%= c.text %></blockquote>		        
     <% end %>  
        <% if user_signed_in? %>
	         <% if c.following(current_user.id) == true %>
		         <%= link_to "following", "#", 'data-id' => UserArtist.get_id_from_content(current_user.id, c.artist_id),  class: "button radius round tiny following_state btnFollow info", 
		         'data-user' => current_user.id,'data-artist' => c.artist.id %>
	         <% else %>
		         <%= link_to "follow", "#" ,class: "button radius round tiny alert btnFollow", 'data-user' => current_user.id, 
		        'data-artist' => c.artist_id, 'data-id'=>"none" %>
	         <% end %>

	         <% if c.favorite(current_user.id) == true %>

		         <%= button_tag "Saved to favorites", class: "button radius round tiny info favorite_state btnFavorite",id: c.id, 
		         'data-user' => current_user.id, 
			       'data-content' => c.favorite_item(c.id, current_user.id) %>	         	
		         <% else %>
		         <%= button_tag "Add to favorites", class: "button radius round tiny success btnFavorite", id: c.id,'data-user' => current_user.id, 'data-content' => c.id %>
		         <% end %>
         <% end %>
         
        <p>
        <%#= link_to "#", 'data-reveal-id' => 'modal', remote: true do %>
			<%= image_tag c.image_url(:main).to_s %>
		<%# end %>
		</p>
	</div>
</div>	 							              
 <% end %>


 
<%= render 'layouts/modal' %>

app/views/home/_contents.html.erb
<% @contents.each do |c| %>
	
<div id='timeline' class='post large-4 columns'>

 <div class="panel contents">			 
  						              
 	<!-- link to below is to activate modal -->
 	<%#= link_to "#", 'data-reveal-id' => 'modal', remote: true do %>
         
 	   <!--  <div class='action_buttons' style='margin:30% 20%;position:absolute'> -->
        <%# if user_signed_in? %>
         
      <div class='action_buttons <%= c.id %> text-center'>
         <%= render partial: "home/action_buttons", locals: { :c => c }  %>         
      </div>
      <%# end %>
     <!-- </div>  -->

      <div class='post_image text-center'>
        <%#= link_to "#", 'data-reveal-id' => 'modal', remote: true do %>
    			<%= image_tag c.image_url(:main).to_s, class: '.test' %>
    		<%# end %>              
  		</div>
      

        <div class='row'>  
          <div class='bottom-info' style='float:left; margin: 10px'>
           <%= link_to user_artists_path(artist_id: c.artist.id) do %>
             <h4><%= c.artist.artist_name %></h4>
             <h5 style='word-wrap:break-word;'><%= c.user_name.to_s + " via " + c.social_media_site.to_s %></h5>
             <h6><%= c.created_at.to_date %></h6>                
           <% end %> 
           </div>
         
           <div class='profile_image' style='float:right'>
             <% if c.twitterposter %>
             <%= image_tag c.twitterposter.profile_image_url(:thumb).to_s, size: '100x100', style: 'margin:10px 16px 0 0' %>
             <% else %>
             <%= image_tag c.instagramposter.profile_image_url(:thumb).to_s, size: '100x100', style: 'margin:10px 16px 0 0'  %>
             <% end %>
           </div>
       </div>

      
      

  
	</div>
</div>

 <% end %>


 
<%= render 'layouts/modal' %>

app/views/home/_instagram.html.erb
<div id='instagram_timelines'>
<%# cache "instagram_timelines#{Date.today}" do %>
	<% @user.each do |ins| %>
	  <%= image_tag ins.images.standard_resolution.url %><br>
	  <strong><%= ins.user.username %> </strong><br>
	  <strong><%= ins.id.slice(0..(ins.id.index('_')-1)) %> </strong><br>
	  <strong><%= ins.caption.to_s.split('text="').last.to_s.slice(0..20) %> </strong><br>
	  <strong><%= Time.at(ins.created_time.to_i) %> </strong><br>
	
	<% end %>
<%# end %>
</div>

app/views/home/_pagination.html.erb
<%= paginate @contents %>

app/views/home/_scoped_contents.html.erb
<% @contents.each do |c| %>

<div id='<%= c.id %>' class='post large-4 columns' >

 	<div class="panel" style='display:block'>			 							              
 	<!-- link to below is to activate modal -->
 	<%#= link_to "#", 'data-reveal-id' => 'modal', remote: true do %>
 	<%= link_to "#",  remote: true do %>
       	<h4><%= c.artist.artist_name %></h4>
        <h5><%= c.user_name.to_s + " via " + c.social_media_site.to_s %></h5>
        <h6><%= c.created_at.to_date %></h6>        
        <blockquote  style='text-overflow: ellipsis;'><%= c.text %></blockquote>		        
     <% end %>  
        <% if user_signed_in? %>	         

	        <div id='buttons_for_<%= c.id %>' class='action_buttons_scoped'><%= render 'home/action_buttons_scoped', :c => c %></div>

         <% end %>
        <p>
        <%#= link_to "#", 'data-reveal-id' => 'modal', remote: true do %>
			<%= image_tag c.image_url(:main).to_s %>
		<%# end %>
		</p>
	</div>
</div>	 							              
 <% end %>


 
<%= render 'layouts/modal' %>

app/views/home/_scoped_contents_artist.html.erb
<% @contents.each do |c| %>

<div id='artist_content_<%= c.id %>' class='post large-4 columns' >

 	<div class="panel contents" style='display:block'>			 							              
 	<!-- link to below is to activate modal -->
 	<%#= link_to "#", 'data-reveal-id' => 'modal', remote: true do %>
 	<%= link_to "#",  remote: true do %>
       	<h4><%= c.artist.artist_name %></h4>
        <h5><%= c.user_name.to_s + " via " + c.social_media_site.to_s %></h5>
        <h6><%= c.created_at.to_date %></h6>        
        <blockquote  style='text-overflow: ellipsis;'><%= c.text %></blockquote>		        
     <% end %>  
        <% if user_signed_in? %>	         

	        <div id='buttons_for_<%= c.id %>' class='action_buttons_scoped'><%= render 'home/action_buttons_scoped', :c => c %></div>

         <% end %>
        <p>
        <%#= link_to "#", 'data-reveal-id' => 'modal', remote: true do %>
			<%= image_tag c.image_url(:main).to_s %>
		<%# end %>
		</p>
	</div>
</div>	 							              
 <% end %>


 
<%= render 'layouts/modal' %>

app/views/home/_scoped_favorites.html.erb
<% @contents.each do |c| %>

<div id='timeline' class='post large-4 columns' >

 	<div class="panel contents" style='display:block'>			 							              
 	<!-- link to below is to activate modal -->
 	<%#= link_to "#", 'data-reveal-id' => 'modal', remote: true do %>
 	<%= link_to "#",  remote: true do %>
       	<h4><%= c.artist.artist_name %></h4>
        <h5><%= c.user_name.to_s + " via " + c.social_media_site.to_s %></h5>
        <h6><%= c.created_at.to_date %></h6>        
        <blockquote  style='text-overflow: ellipsis;'><%= c.text %></blockquote>		        
     <% end %>  
        <% if user_signed_in? %>	         

	          <% if c.favorite(current_user.id) == true %>

            <% if params[:artist_id] %>
                <%= link_to "Remove from favorites", user_content_path(UserContent.where(:user_id=>current_user.id).where(:content_id=>c.id).first.id, :scoped_favorite=>true, artist_id: c.artist_id), 
                method: 'delete', class: 'button radius round tiny info', remote: true %> 
            <% else  %>
                <%= link_to "Remove from favorites", user_content_path(UserContent.where(:user_id=>current_user.id).where(:content_id=>c.id).first.id, :scoped_favorite=>true), 
                method: 'delete', class: 'button radius round tiny info', remote: true %> 
            <% end %>

             <% else %>
            

             <%= link_to "Add to favorites", user_contents_path(user_content: 
             {user_id: current_user.id, content_id: c.id, artist_id: c.artist_id},:scoped_favorite=>true), 
             method: 'post', action: :create, class: 'button radius round tiny success', remote: true %>

           <% end %>

         <% end %>
        <p>
        <%#= link_to "#", 'data-reveal-id' => 'modal', remote: true do %>
			<%= image_tag c.image_url(:main).to_s %>
		<%# end %>
		</p>
	</div>
</div>	 							              
 <% end %>


 
<%= render 'layouts/modal' %>

app/views/home/_search_form.html.erb
   

<%= form_tag home_index_path, :method=>'GET', :id=>'frmSearch' do  %>
<li class="has-form large-3 columns" style='margin-top:5px'> 
    <div class="row collapse"> 

   <div class="large-8 medium-6 small-6 columns"> 
      <!-- <input type="text" placeholder="search anything">      -->
      <%= text_field_tag "search_field", nil, placeholder: "search anything...", value: params[:search_field] %>
  </div> 
  <div class="large-2 medium-3 small-3 columns"> 
    <%= submit_tag "Search", id: 'btnSearch', name: 'search', class: "button expand" %>    
  </div>
  <div class="large-2 medium-3 small-3 columns">
  	<%= submit_tag "Clear", id: 'btnClear',  name: 'clear', class: "alert button expand" %> 
  </div>
 </div>
</li> 
 <% end %>

 

app/views/home/index.html.erb
<%# content_for :user_image do %>
  <%#= image_tag(@client.profile_image_url_https(:bigger))%>      
<%# end %> 



<div class='row'>
  <div id='posts' class="posts active" id="panel2-1">
    <%= render 'contents' %>
  </div>
 </div>



<p><div class='pagination_scroll row large-12 columns' style='margin-top:30px;'>
<%= render 'pagination' %>
</div></p>

<script type="text/javascript">


// $('#text_content').find('a').each(function() {
//     $(this).attr("target", "_blank");
// });
// toggleScroll("posts", "post");

// $element = $('#posts')

//   $element.infinitescroll({
 
//     navSelector  : "nav.pagination",            
//                    // selector for the paged navigation (it will be hidden)
//     nextSelector : "nav.pagination a[rel=next]",    
//                    // selector for the NEXT link (to page 2)
//     itemSelector : "#posts div.post",

//     loading: {          
//           img: '../assets/loading.gif',                              
//           finished: undefined,
//           msgText: "",
//           finishedMsg: "",
//           selector: '#loader',
//           speed: 'fast'
//     }

   
//  });





</script>

app/views/home/index.js.erb
$("#flash_messages").html("<%= escape_javascript(render('layouts/messages')) %>");

$("#posts").html("<%= escape_javascript(render('content')) %>");

$(".pagination_scroll").html("<%= escape_javascript(render('pagination')) %>");
// 