config/routes.rb
Rails.application.routes.draw do
  
  resources :user_contents do
    collection do
      get "user_contents_count" 
    end
  end

  resources :user_artists do
     collection do
      get "user_artists_count" 
      get "artist_index"
    end
  end
    
  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  namespace :admin do 
    resources :instagramposters, :twitterposters, :artists
  end

  get 'home/index'

  root 'home#index'

end

app/models/instagramposter.rb
class Instagramposter < ActiveRecord::Base
	belongs_to :artist
	has_many :contents
	
	mount_uploader :profile_image, ProfileImageUploader
end

app/controllers/admin/instagramposters_controller.rb
module Admin

class InstagrampostersController < ApplicationController
  
  # http_basic_authenticate_with name: Rails.application.secrets.admin_name, password: Rails.application.secrets.admin_password
  before_action :set_instagramposter, only: [:show, :edit, :update, :destroy]
  before_filter :admin_authentication

  # GET /instagramposters
  # GET /instagramposters.json
  def index
    @instagramposters = Instagramposter.all
  end

  # GET /instagramposters/1
  # GET /instagramposters/1.json
  def show
  end

  # GET /instagramposters/new
  def new
    @instagramposter = Instagramposter.new
  end

  # GET /instagramposters/1/edit
  def edit
  end

  # POST /instagramposters
  # POST /instagramposters.json
  def create
    @instagramposter = Instagramposter.new(instagramposter_params)

    respond_to do |format|
      if @instagramposter.save
        format.html { redirect_to [:admin, @instagramposter], notice: 'Instagramposter was successfully created.' }
        format.json { render :show, status: :created, location: @instagramposter }
      else
        format.html { render :new }
        format.json { render json: @instagramposter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instagramposters/1
  # PATCH/PUT /instagramposters/1.json
  def update
    respond_to do |format|
      if @instagramposter.update(instagramposter_params)
        format.html { redirect_to [:admin, @instagramposter], notice: 'Instagramposter was successfully updated.' }
        format.json { render :show, status: :ok, location: @instagramposter }
      else
        format.html { render :edit }
        format.json { render json: @instagramposter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instagramposters/1
  # DELETE /instagramposters/1.json
  def destroy
    @instagramposter.destroy
    respond_to do |format|
      format.html { redirect_to [:admin, instagramposters_url], notice: 'Instagramposter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instagramposter
      @instagramposter = Instagramposter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instagramposter_params
      params.require(:instagramposter).permit(:ig_id, :screen_name, :artist_id, :profile_image,:remote_profile_image_url)
    end
end
end

app/helpers/instagramposters_helper.rb
module InstagrampostersHelper
end

app/views/admin/instagramposters/_form.html.erb
<%= form_for [:admin, @instagramposter] do |f| %>
  <% if @instagramposter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@instagramposter.errors.count, "error") %> prohibited this instagramposter from being saved:</h2>

      <ul>
      <% @instagramposter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ig_id %><br>
    <%= f.number_field :ig_id %>
  </div>
  <div class="field">
    <%= f.label :screen_name %><br>
    <%= f.text_field :screen_name %>
  </div>
  <div class="field">
   <%= f.label :artist_id %><br>
    <%= f.select :artist_id, Artist.all.collect{ |u| [u.artist_name, u.id] }, include_blank: true %>
  </div>
  
  <div class="field">
    <%= f.label :remote_profile_image_url %><br>
    <%= f.text_field :remote_profile_image_url %>   
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/instagramposters/edit.html.erb
<h1>Editing instagramposter</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_instagramposter_path(@instagramposter) %> |
<%= link_to 'Back', admin_instagramposters_path %>

app/views/admin/instagramposters/index.html.erb
<h1>Listing instagramposters</h1>

<table>
  <thead>
    <tr>
      <th>Ig</th>
      <th>Screen name</th>
      <th>Poster</th>
      <th>Profile Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instagramposters.each do |instagramposter| %>
      <tr>
        <td><%= instagramposter.ig_id %></td>
        <td><%= instagramposter.screen_name %></td>
        <td><%= instagramposter.artist.artist_name %></td>
        <td><%= image_tag instagramposter.profile_image %></td>
        <td><%= link_to 'Show', admin_instagramposter_path(instagramposter) %></td>
        <td><%= link_to 'Edit', edit_admin_instagramposter_path(instagramposter) %></td>
        <td><%= link_to 'Destroy', admin_instagramposter_path(instagramposter), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Instagramposter', new_admin_instagramposter_path %>

app/views/admin/instagramposters/new.html.erb
<h1>New instagramposter</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_instagramposters_path %>

app/views/admin/instagramposters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ig:</strong>
  <%= @instagramposter.ig_id %>
</p>

<p>
  <strong>Screen name:</strong>
  <%= @instagramposter.screen_name %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @instagramposter.artist.artist_name %>
</p>

<p>
  <strong>Profile Image:</strong>
  <%= image_tag @instagramposter.profile_image %>
</p>

<%= link_to 'Edit', edit_admin_instagramposter_path(@instagramposter) %> |
<%= link_to 'Back', admin_instagramposters_path %>